version: '3.1'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_bookstore
    ports:
      - 5434:5432
    volumes:
      - pgsql-data:/var/lib/postgresql/data

volumes:
  pgsql-data:
